[package]
name = "n-puzzle"
version = "0.9.0"
authors = ["McM1k <gboudrie@student.42.fr>", "Raokk <vroussea@student.42.fr>"]
edition = "2018"

[dependencies]
rand = "0.6"
structopt = "0.2.16"
clap = { version = "2.33", default-features = false }
strum = "0.15.0"
strum_macros = "0.15.0"